//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMPLOI_ARASL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Chomeur
    {
        public int Id { get; set; }
        public string nom { get; set; }
        public string prenom { get; set; }
        public System.DateTime dob { get; set; }
        public string villagenaiss { get; set; }
        public int tel { get; set; }
        public string mail { get; set; }
        public string lieuresidenc { get; set; }
        public string diplome { get; set; }
        public string formation { get; set; }
        public bool employe { get; set; }
        public bool actif { get; set; }
    }
}
